### ISSUE TITLE
运行项目报错啊

### ISSUE THREAD

**Issue by 812781385** [Chinvoxel/vue3-admin-template#1]
我使用windows电脑成功安装依赖后，pnpm dev时出现：
[plugin:vite:css] [sass] Can't find stylesheet to import.
  ╷
2 │           @use 'D:\opt\jimei2\src\styles\mixin.scss' as *;
  │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\styles\index.scss 2:11  root stylesheet

**Comment by Chinvoxel** [comment]
1. 请确认本地node版本为18.x.x
2. 尝试手动安装sass依赖或删除node_modules重新安装依赖
3. 请确保存该路径下存在此文件D:\opt\jimei2\styles\mixin.scss

**Comment by 812781385** [comment]
> 1. 请确认本地节点版本为18.xx
> 2. 尝试手动安装 sass 依赖或删除node_modules重新安装依赖
> 3. 请确保存放该路径下存在此文件D:\opt\jimei2\styles\mixin.scss

vite里css配置的问题，正确的应该是：
```
css: {
      preprocessorOptions: {
        scss: {
          additionalData: `@use "@/styles/mixin.scss" as *;@use "@/styles/variables.scss" as *;@use "@/styles/element/index.scss" as *;`
        }
      }
```
